import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./nav/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Log Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <Nav />
        <div className={inter.className}>{children}</div>
      </body>
    </html>
  );
}
